"""Add Lead table and separate WhatsApp logic

Revision ID: 11595cdc690d
Revises: 3244e7d73700
Create Date: 2026-04-09 12:11:41.376151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11595cdc690d'
down_revision: Union[str, None] = '3244e7d73700'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('whatsapp_template_status', sa.String(), nullable=True),
    sa.Column('transferred_to_agent', sa.Boolean(), nullable=True),
    sa.Column('is_converted', sa.Boolean(), nullable=True),
    sa.Column('guest_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['guest_id'], ['guest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_id'), 'lead', ['id'], unique=False)
    op.create_index(op.f('ix_lead_phone'), 'lead', ['phone'], unique=True)
    op.add_column('conversation', sa.Column('lead_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'conversation', 'lead', ['lead_id'], ['id'])
    op.drop_column('guest', 'transferred_to_agent')
    op.drop_column('guest', 'whatsapp_template_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guest', sa.Column('whatsapp_template_status', sa.VARCHAR(), server_default=sa.text("'NOT_SENT'::character varying"), autoincrement=False, nullable=True))
    op.add_column('guest', sa.Column('transferred_to_agent', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'conversation', type_='foreignkey')
    op.drop_column('conversation', 'lead_id')
    op.drop_index(op.f('ix_lead_phone'), table_name='lead')
    op.drop_index(op.f('ix_lead_id'), table_name='lead')
    op.drop_table('lead')
    # ### end Alembic commands ###
