"""Add AIAudit table

Revision ID: 1bfa5cc3e82c
Revises: 7452fe033854
Create Date: 2026-04-06 13:06:55.431658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bfa5cc3e82c'
down_revision: Union[str, None] = '7452fe033854'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_audit_id'), 'ai_audit', ['id'], unique=False)
    op.create_index(op.f('ix_ai_audit_model_name'), 'ai_audit', ['model_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_audit_model_name'), table_name='ai_audit')
    op.drop_index(op.f('ix_ai_audit_id'), table_name='ai_audit')
    op.drop_table('ai_audit')
    # ### end Alembic commands ###
