"""Add is_deleted to PropertyAsset

Revision ID: 3244e7d73700
Revises: 80a21f7e8e27
Create Date: 2026-04-09 11:41:53.553833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3244e7d73700'
down_revision: Union[str, None] = '80a21f7e8e27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_asset', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_property_asset_is_deleted'), 'property_asset', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_property_asset_is_deleted'), table_name='property_asset')
    op.drop_column('property_asset', 'is_deleted')
    # ### end Alembic commands ###
