"""Remove legacy tables

Revision ID: 37431a1c1f98
Revises: f36477d3fd43
Create Date: 2026-04-06 18:22:46.111552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37431a1c1f98'
down_revision: Union[str, None] = 'f36477d3fd43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_booking_id'), table_name='booking')
    op.drop_table('booking')
    op.drop_index(op.f('ix_room_id'), table_name='room')
    op.drop_index(op.f('ix_room_room_number'), table_name='room')
    op.drop_table('room')
    op.drop_index(op.f('ix_property_id'), table_name='property')
    op.drop_index(op.f('ix_property_location'), table_name='property')
    op.drop_index(op.f('ix_property_name'), table_name='property')
    op.drop_table('property')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('property_pkey'))
    )
    op.create_index(op.f('ix_property_name'), 'property', ['name'], unique=False)
    op.create_index(op.f('ix_property_location'), 'property', ['location'], unique=False)
    op.create_index(op.f('ix_property_id'), 'property', ['id'], unique=False)
    op.create_table('room',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('room_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price_per_night', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('capacity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], name=op.f('room_property_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('room_pkey'))
    )
    op.create_index(op.f('ix_room_room_number'), 'room', ['room_number'], unique=False)
    op.create_index(op.f('ix_room_id'), 'room', ['id'], unique=False)
    op.create_table('booking',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('check_in_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('check_out_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('total_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], name=op.f('booking_room_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('booking_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('booking_pkey'))
    )
    op.create_index(op.f('ix_booking_id'), 'booking', ['id'], unique=False)
    # ### end Alembic commands ###
