"""Add geographical metadata fields to property assets

Revision ID: 80a21f7e8e27
Revises: cf304109821f
Create Date: 2026-04-07 14:55:00.323256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80a21f7e8e27'
down_revision: Union[str, None] = 'cf304109821f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_asset', sa.Column('location_name', sa.String(), nullable=True))
    op.add_column('property_asset', sa.Column('landmark', sa.String(), nullable=True))
    op.add_column('property_asset', sa.Column('map_link', sa.String(), nullable=True))
    op.add_column('property_asset', sa.Column('description', sa.String(), nullable=True))
    op.create_index(op.f('ix_property_asset_location_name'), 'property_asset', ['location_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_property_asset_location_name'), table_name='property_asset')
    op.drop_column('property_asset', 'description')
    op.drop_column('property_asset', 'map_link')
    op.drop_column('property_asset', 'landmark')
    op.drop_column('property_asset', 'location_name')
    # ### end Alembic commands ###
