"""Link Reservation to User

Revision ID: a2b4b70e503a
Revises: 37431a1c1f98
Create Date: 2026-04-06 18:25:46.583772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2b4b70e503a'
down_revision: Union[str, None] = '37431a1c1f98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reservation', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reservation', type_='foreignkey')
    op.drop_column('reservation', 'user_id')
    # ### end Alembic commands ###
