"""Add PropertyAsset model

Revision ID: a7d595eaa73e
Revises: 1bfa5cc3e82c
Create Date: 2026-04-06 15:03:24.639526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7d595eaa73e'
down_revision: Union[str, None] = '1bfa5cc3e82c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('cleaning_status', sa.String(), nullable=True),
    sa.Column('base_price', sa.Float(), nullable=True),
    sa.Column('max_adults', sa.Integer(), nullable=True),
    sa.Column('max_children', sa.Integer(), nullable=True),
    sa.Column('extra_beds_limit', sa.Integer(), nullable=True),
    sa.Column('breakfast_included', sa.Boolean(), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bed_config', sa.String(), nullable=True),
    sa.Column('floor', sa.String(), nullable=True),
    sa.Column('view', sa.String(), nullable=True),
    sa.Column('pool_type', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_asset_cleaning_status'), 'property_asset', ['cleaning_status'], unique=False)
    op.create_index(op.f('ix_property_asset_id'), 'property_asset', ['id'], unique=False)
    op.create_index(op.f('ix_property_asset_name'), 'property_asset', ['name'], unique=False)
    op.create_index(op.f('ix_property_asset_status'), 'property_asset', ['status'], unique=False)
    op.create_index(op.f('ix_property_asset_type'), 'property_asset', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_property_asset_type'), table_name='property_asset')
    op.drop_index(op.f('ix_property_asset_status'), table_name='property_asset')
    op.drop_index(op.f('ix_property_asset_name'), table_name='property_asset')
    op.drop_index(op.f('ix_property_asset_id'), table_name='property_asset')
    op.drop_index(op.f('ix_property_asset_cleaning_status'), table_name='property_asset')
    op.drop_table('property_asset')
    # ### end Alembic commands ###
