"""Add AssetImage table for multiple images

Revision ID: cd5a2a0b7b26
Revises: a7d595eaa73e
Create Date: 2026-04-06 15:18:26.423224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd5a2a0b7b26'
down_revision: Union[str, None] = 'a7d595eaa73e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_cover', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['property_asset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_image_id'), 'asset_image', ['id'], unique=False)
    op.drop_column('property_asset', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_asset', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_asset_image_id'), table_name='asset_image')
    op.drop_table('asset_image')
    # ### end Alembic commands ###
