"""Add Guest table and link Reservations

Revision ID: f36477d3fd43
Revises: 6115dca342b1
Create Date: 2026-04-06 16:12:21.111076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f36477d3fd43'
down_revision: Union[str, None] = '6115dca342b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('id_proof_type', sa.String(), nullable=True),
    sa.Column('id_number', sa.String(), nullable=False),
    sa.Column('id_proof_image_url', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('total_stays', sa.Integer(), nullable=True),
    sa.Column('loyalty_tier', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guest_email'), 'guest', ['email'], unique=True)
    op.create_index(op.f('ix_guest_id'), 'guest', ['id'], unique=False)
    op.create_index(op.f('ix_guest_phone'), 'guest', ['phone'], unique=True)
    op.add_column('reservation', sa.Column('guest_id', sa.Integer(), nullable=True))
    op.alter_column('reservation', 'guest_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'reservation', 'guest', ['guest_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reservation', type_='foreignkey')
    op.alter_column('reservation', 'guest_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('reservation', 'guest_id')
    op.drop_index(op.f('ix_guest_phone'), table_name='guest')
    op.drop_index(op.f('ix_guest_id'), table_name='guest')
    op.drop_index(op.f('ix_guest_email'), table_name='guest')
    op.drop_table('guest')
    # ### end Alembic commands ###
